In [1]:
#TITLE CELL
# Assignment: Classification Algorithms on Two Kaggle Datasets
# Name: Ananya
# Subject: Machine Learning
# Date: 31-03-2026

In [2]:
!pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.4.4)
Requirement already satisfied: scikit-learn in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import sys
print(sys.executable)

C:\Users\A\AppData\Local\Programs\Python\Python311\python.exe

In [4]:
"{sys.executable}"

'{sys.executable}'

In [5]:
#SECTION 1: IMPORT LIBRARIES
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
import os
print(os.getcwd())

C:\Users\A\classification-model-benchmarking\notebooks

In [7]:
#SECTION 2: TITANIC DATASET
#2.1Load Titanic Dataset
df = pd.read_csv("../datasets/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
#2.2 Dataset Info
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
#2.3 Preprocessing Titanic Dataset
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Fare'] = df['Fare'].fillna(df['Fare'].median())

df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [10]:
#2.4 Titanic Train-Test Split
X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
#2.5 Apply All Algorithms on Titanic
#Logistic Regression
lr = LogisticRegression()
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)
print("Titanic - Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

Titanic - Logistic Regression Accuracy: 0.8044692737430168

In [12]:
#SVM
svm = SVC()
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)
print("Titanic - SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

Titanic - SVM Accuracy: 0.8156424581005587

In [13]:
#Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print("Titanic - Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Titanic - Random Forest Accuracy: 0.8212290502793296

In [14]:
#Naive Bayes
nb = GaussianNB()
nb.fit(X_train_scaled, y_train)
y_pred_nb = nb.predict(X_test_scaled)
print("Titanic - Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))

Titanic - Naive Bayes Accuracy: 0.776536312849162

In [15]:
#KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)
print("Titanic - KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

Titanic - KNN Accuracy: 0.8044692737430168

In [16]:
#Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

print("Titanic - Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Titanic - Decision Tree Accuracy: 0.7821229050279329
[[83 22]
 [17 57]]
              precision    recall  f1-score   support

           0       0.83      0.79      0.81       105
           1       0.72      0.77      0.75        74

    accuracy                           0.78       179
   macro avg       0.78      0.78      0.78       179
weighted avg       0.79      0.78      0.78       179

In [17]:
#2.6 Titanic Accuracy Table
results_titanic = pd.DataFrame({
    'Algorithm': ['Logistic Regression', 'SVM', 'Random Forest', 'Naive Bayes', 'KNN', 'Decision Tree'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_svm),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_nb),
        accuracy_score(y_test, y_pred_knn),
        accuracy_score(y_test, y_pred_dt)
    ]
})

results_titanic

             Algorithm  Accuracy
0  Logistic Regression  0.804469
1                  SVM  0.815642
2        Random Forest  0.821229
3          Naive Bayes  0.776536
4                  KNN  0.804469
5        Decision Tree  0.782123

In [18]:
#SECTION 3: DIABETES DATASET
#3.1 Load Diabetes Dataset
df2 = pd.read_csv("../datasets/diabetes.csv")
df2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [19]:
#3.2 Dataset Info
df2.info()
df2.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [20]:
#3.3 Diabetes Train-Test Split
X = df2.drop('Outcome', axis=1)
y = df2['Outcome']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
#3.4 Apply All Algorithms on Diabetes
#Logistic Regression
lr = LogisticRegression()
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)
print("Diabetes - Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

Diabetes - Logistic Regression Accuracy: 0.7532467532467533

In [22]:
#SVM
svm = SVC()
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)
print("Diabetes - SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

Diabetes - SVM Accuracy: 0.7337662337662337

In [23]:
#Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print("Diabetes - Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Diabetes - Random Forest Accuracy: 0.7207792207792207

In [24]:
#Naives Bayes
nb = GaussianNB()
nb.fit(X_train_scaled, y_train)
y_pred_nb = nb.predict(X_test_scaled)
print("Diabetes - Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))

Diabetes - Naive Bayes Accuracy: 0.7662337662337663

In [25]:
#KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)
print("Diabetes - KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

Diabetes - KNN Accuracy: 0.6948051948051948

In [26]:
#DecisionTree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

print("Diabetes - Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Diabetes - Decision Tree Accuracy: 0.7467532467532467
[[75 24]
 [15 40]]
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        99
           1       0.62      0.73      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154

In [27]:
#3.6 Diabetes Accuracy Table
results_diabetes = pd.DataFrame({
    'Algorithm': ['Logistic Regression', 'SVM', 'Random Forest', 'Naive Bayes', 'KNN', 'Decision Tree'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_svm),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_nb),
        accuracy_score(y_test, y_pred_knn),
        accuracy_score(y_test, y_pred_dt)
    ]
})

results_diabetes

             Algorithm  Accuracy
0  Logistic Regression  0.753247
1                  SVM  0.733766
2        Random Forest  0.720779
3          Naive Bayes  0.766234
4                  KNN  0.694805
5        Decision Tree  0.746753



Conclusion:
In this assignment, classification algorithms were applied on two Kaggle datasets:
1. Titanic Dataset
2. Diabetes Dataset

The following classification algorithms were used:
- Logistic Regression
- SVM
- Random Forest
- Naive Bayes
- KNN
- Decision Tree

The performance of all models was evaluated using accuracy score, confusion matrix, and classification report.
This assignment helped in understanding how different classification algorithms perform on different datasets.